import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:8081/');
  await page.getByRole('img', { name: 'closed' }).click();
  await page.getByRole('button', { name: 'Login' }).click();
  await page.locator('input[type="email"]').click();
  await page.locator('input[type="email"]').fill('\'emily.johnson@x.dummyjson.com');
  await page.locator('input[type="email"]').press('ArrowLeft');
  await page.locator('input[type="email"]').press('ArrowLeft');
  await page.locator('input[type="email"]').press('ArrowLeft');
  await page.locator('input[type="email"]').press('ArrowLeft');
  await page.locator('input[type="email"]').press('ArrowLeft');
  await page.locator('input[type="email"]').press('ArrowLeft');
  await page.locator('input[type="email"]').press('ArrowLeft');
  await page.locator('input[type="email"]').press('ArrowLeft');
  await page.locator('input[type="email"]').press('ArrowLeft');
  await page.locator('input[type="email"]').press('ArrowLeft');
  await page.locator('input[type="email"]').press('ArrowLeft');
  await page.locator('input[type="email"]').press('ArrowLeft');
  await page.locator('input[type="email"]').press('ArrowLeft');
  await page.locator('input[type="email"]').press('ArrowLeft');
  await page.locator('input[type="email"]').press('ArrowLeft');
  await page.locator('input[type="email"]').press('ArrowLeft');
  await page.locator('input[type="email"]').press('ArrowLeft');
  await page.locator('input[type="email"]').press('ArrowLeft');
  await page.locator('input[type="email"]').press('ArrowLeft');
  await page.locator('input[type="email"]').press('ArrowLeft');
  await page.locator('input[type="email"]').press('ArrowLeft');
  await page.locator('input[type="email"]').press('ArrowLeft');
  await page.locator('input[type="email"]').press('ArrowLeft');
  await page.locator('input[type="email"]').press('ArrowLeft');
  await page.locator('input[type="email"]').press('ArrowLeft');
  await page.locator('input[type="email"]').press('ArrowLeft');
  await page.locator('input[type="email"]').press('ArrowLeft');
  await page.locator('input[type="email"]').press('ArrowLeft');
  await page.locator('input[type="email"]').press('ArrowLeft');
  await page.locator('input[type="email"]').press('ArrowRight');
  await page.locator('input[type="email"]').press('ArrowLeft');
  await page.locator('input[type="email"]').fill('emily.johnson@x.dummyjson.com');
  await page.locator('input[type="password"]').click();
  await page.locator('input[type="password"]').fill('emilyspass');
  await page.locator('form').getByRole('button', { name: 'Login' }).click();
  await page.getByRole('img', { name: 'open' }).click();
  await page.getByRole('button', { name: 'Logout' }).click();
});